"""
engine/workflow/strategy_approval.py — Prompt 20

Manages the approval lifecycle of strategies generated by Prompt 13.
Strategies default to 'pending' until a user with 'approve_strategy' 
permission formally approves them.
"""

import pandas as pd
from pathlib import Path
from datetime import datetime
import json
import logging
from typing import List, Dict, Any, Optional
import os

log = logging.getLogger(__name__)

class StrategyApprovalManager:
    def __init__(self, root_dir: Path):
        self.root_dir = Path(root_dir)
        self.approvals_path = self.root_dir / "derived" / "workflow" / "strategy_approvals.csv"
        self._ensure_file()

    def _ensure_file(self):
        """Creates the approvals CSV if it doesn't exist."""
        self.approvals_path.parent.mkdir(parents=True, exist_ok=True)
        if not self.approvals_path.exists():
            df = pd.DataFrame(columns=[
                "strategy_id", "status", "approved_by", 
                "approval_timestamp", "notes"
            ])
            df.to_csv(self.approvals_path, index=False)

    def load_approvals(self) -> pd.DataFrame:
        """Load the current approval ledger."""
        if self.approvals_path.exists():
            return pd.read_csv(self.approvals_path)
        return pd.DataFrame()

    def get_approval_status(self, strategy_id: str) -> str:
        """Returns the current status of a strategy (pending, approved, rejected)."""
        df = self.load_approvals()
        if df.empty or strategy_id not in df["strategy_id"].values:
            return "pending"
        
        # Get latest action
        record = df[df["strategy_id"] == strategy_id].iloc[-1]
        return record["status"]

    def submit_approval(self, strategy_id: str, user_id: str, status: str, notes: str = "") -> bool:
        """
        Record an approval decision (approved or rejected).
        The caller (auth_manager) should verify permissions before calling this.
        """
        if status not in ["approved", "rejected", "pending"]:
            raise ValueError(f"Invalid status: {status}")

        df = self.load_approvals()
        new_row = {
            "strategy_id": strategy_id,
            "status": status,
            "approved_by": user_id,
            "approval_timestamp": datetime.utcnow().isoformat(),
            "notes": notes
        }
        
        # Append logic (allow history of decisions via tail)
        df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
        df.to_csv(self.approvals_path, index=False)
        log.info(f"Strategy {strategy_id} marked {status} by {user_id}")
        return True

    def get_pending_strategies(self) -> List[str]:
        """Return a list of strictly pending strategies."""
        df = self.load_approvals()
        if df.empty:
            return []
        
        # Get latest status per strategy
        latest = df.sort_values("approval_timestamp").groupby("strategy_id").tail(1)
        pending = latest[latest["status"] == "pending"]
        return pending["strategy_id"].tolist()
