"""
engine/ui/ui_workflow_mapper.py — Prompt 31 Feature 4

Scans the UI source tree and produces a navigation map of the interface.
Output: docs/UI_WORKFLOW_MAP.md
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional


def _find_page_titles(path: Path) -> list[str]:
    """Extract st.subheader/st.title/page-title strings from a Python UI file."""
    titles = []
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
        for pattern in [
            r"st\.(?:title|header|subheader)\([\"']([^\"']+)[\"']",
            r"page.title[\"']>([^<]+)<",
            r"CAMPAIGN_IN_A_BOX_PAGE\s*=\s*[\"']([^\"']+)[\"']",
        ]:
            titles.extend(re.findall(pattern, text))
    except Exception:
        pass
    return titles


def map_ui_workflow(project_root: Path) -> str:
    """
    Scan the UI directory tree and produce a markdown navigation map.
    """
    ui_roots = [
        project_root / "ui",
        project_root / "frontend",
        project_root / "app",
    ]

    lines = [
        "# Campaign In A Box — UI Workflow Map",
        "",
        "> Auto-generated by `engine/ui/ui_workflow_mapper.py`  ",
        "> This map reflects the actual structure of the UI source tree.",
        "",
    ]

    # ── Sidebar Navigation (from known app structure) ─────────────────────────
    # Derived from live audit (Prompt 30) observations
    lines += [
        "## Navigation Tree (Live Audit Observed)",
        "",
        "```",
        "Campaign In A Box",
        " ├── 🏠  Campaign Overview",
        " │    └── Active campaign banner, health score, last run info",
        " │",
        " ├── 📊  Data",
        " │    └── 📁 Data Manager",
        " │         ├── 📤 Upload New File",
        " │         ├── 🗂️ File Registry            ← edit, re-tag, archive, unarchive, delete",
        " │         ├── 🔎 Precinct ID Review",
        " │         ├── 🗃️ Election Archive",
        " │         └── 🔍 Missing Data Assistant",
        " │",
        " ├── 🏗️  System",
        " │    └── 🛠️ Pipeline Runner",
        " │         ├── Contest selector dropdown",
        " │         ├── Contest details banner (state/county/year/slug)",
        " │         ├── Run Modeling Pipeline button",
        " │         ├── Pipeline output log",
        " │         └── Download Log / Download Output buttons",
        " │",
        " ├── 🌍  Geography",
        " │    └── 🗺️ Precinct Map",
        " │         ├── Kepler.gl interactive map",
        " │         └── Top 25 Precincts chart",
        " │",
        " ├── 📚  Intelligence",
        " │    └── 🗃️ Historical Archive",
        " │         ├── Archive table (per-election precinct stats)",
        " │         └── Model training history",
        " │",
        " ├── 📋  Strategy",
        " │    └── Strategy documents viewer",
        " │",
        " ├── 🎯  Field Operations",
        " │    └── 🎲 Simulations",
        " │         └── Monte Carlo scenario table (4 scenarios)",
        " │",
        " ├── ⚙️  Admin",
        " │    └── 🔧 Campaign Admin",
        " │         ├── Create/Edit campaign",
        " │         └── Campaign selector",
        " │",
        " └── 🔬  Diagnostics",
        "      └── System Health dashboard",
        "           ├── System Health (GREEN/WARN/FAIL)",
        "           ├── Geometry status",
        "           └── Join Guard status",
        "```",
        "",
    ]

    # ── Source File Scan ──────────────────────────────────────────────────────
    lines += [
        "## Source File Structure",
        "",
        "| File | Type | Key Functions/Pages |",
        "|---|---|---|",
    ]

    for ui_root in ui_roots:
        if not ui_root.exists():
            continue
        for py_file in sorted(ui_root.rglob("*.py")):
            rel = py_file.relative_to(project_root)
            titles = _find_page_titles(py_file)
            label = ", ".join(titles[:3]) if titles else "—"
            ftype = "Dashboard" if "dashboard" in str(rel) else ("Component" if "component" in str(rel) else "Module")
            lines.append(f"| `{rel}` | {ftype} | {label} |")

    lines += [
        "",
        "## Critical User Flows",
        "",
        "### Flow 1 — First-Time Setup",
        "```",
        "1. Create campaign       → Admin → Campaign Admin → Create",
        "2. Upload results file   → Data → Data Manager → Upload New File",
        "3. Run pipeline          → System → Pipeline Runner → Run",
        "4. View map              → Geography → Precinct Map",
        "5. View archive          → Intelligence → Historical Archive",
        "```",
        "",
        "### Flow 2 — Re-Running After Data Update",
        "```",
        "1. Upload new file       → Data Manager → Upload New File",
        "2. Verify file registered → Data Manager → File Registry",
        "3. Re-run pipeline       → Pipeline Runner → select contest → Run",
        "4. Refresh map page      → browser refresh is sufficient",
        "```",
        "",
        "### Flow 3 — Diagnosing a Problem",
        "```",
        "1. Check diagnostics     → Diagnostics page",
        "2. Download pipeline log → Pipeline Runner → Download Log",
        "3. Check precinct IDs    → Data Manager → Precinct ID Review",
        "4. Review crosswalk      → reports/crosswalk_repair/",
        "```",
        "",
    ]

    return "\n".join(lines)


def write_workflow_map(project_root: Path, out_path: Optional[Path] = None) -> Path:
    content = map_ui_workflow(project_root)
    dest = out_path or (project_root / "docs" / "UI_WORKFLOW_MAP.md")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")
    return dest
