"""
engine/strategy/strategy_exporter.py — Prompt 13

Assembles a portable campaign plan export bundle in:
  reports/export/<run_id>__campaign_plan/

Contents:
  campaign_strategy.md
  vote_path.csv
  field_strategy.csv
  budget_allocation.csv
  persuasion_targets.csv
  gotv_targets.csv
  risk_analysis.csv
  (optional) campaign_config.yaml

Also optionally creates a ZIP archive for download.
"""
from __future__ import annotations

import logging
import shutil
from pathlib import Path
from typing import Optional

BASE_DIR    = Path(__file__).resolve().parent.parent.parent
EXPORT_DIR  = BASE_DIR / "reports" / "export"
STRATEGY_DIR = BASE_DIR / "derived" / "strategy"
REPORTS_DIR  = BASE_DIR / "reports" / "strategy"

log = logging.getLogger(__name__)


def _find_latest(directory: Path, pattern: str) -> Optional[Path]:
    """Return the most recently modified file matching pattern."""
    try:
        matches = sorted(directory.glob(pattern), key=lambda p: p.stat().st_mtime, reverse=True)
        return matches[0] if matches else None
    except Exception:
        return None


def build_export_bundle(run_id: str, create_zip: bool = True) -> dict:
    """
    Assemble all strategy outputs into a portable bundle directory.

    Returns dict with:
      bundle_dir: Path to the export directory
      zip_path: Path to the ZIP archive (if create_zip=True)
      files: list of included files
    """
    bundle_dir = EXPORT_DIR / f"{run_id}__campaign_plan"
    bundle_dir.mkdir(parents=True, exist_ok=True)

    included = []
    skipped  = []

    # File manifest: (source_pattern or path, target filename)
    manifest = [
        # Strategy report
        (REPORTS_DIR    / f"{run_id}__campaign_strategy.md", "campaign_strategy.md"),
        # Strategy CSVs
        (STRATEGY_DIR   / f"{run_id}__vote_path.csv",        "vote_path.csv"),
        (STRATEGY_DIR   / f"{run_id}__field_strategy.csv",   "field_strategy.csv"),
        (STRATEGY_DIR   / f"{run_id}__budget_allocation.csv","budget_allocation.csv"),
        (STRATEGY_DIR   / f"{run_id}__risk_analysis.csv",    "risk_analysis.csv"),
        # Voter targeting (from Prompt 12 strategy pack)
        (BASE_DIR / "derived" / "voter_segments" / f"{run_id}__targeting_quadrants.csv", "targeting_quadrants.csv"),
        # Campaign config
        (BASE_DIR / "config" / "campaign_config.yaml",        "campaign_config.yaml"),
    ]

    # Latest persuasion/GOTV targets (may be from different run)
    for pattern, name in [
        ("*__targeting_quadrants.csv", "persuasion_targets.csv"),  # reuse quadrant CSV
    ]:
        latest = _find_latest(BASE_DIR / "derived" / "voter_segments", pattern)
        if latest:
            manifest.append((latest, name))

    for src, dest_name in manifest:
        if isinstance(src, Path) and src.exists():
            dest = bundle_dir / dest_name
            shutil.copy2(src, dest)
            included.append(dest_name)
            log.info(f"[EXPORTER] Included: {dest_name}")
        else:
            skipped.append(dest_name)

    # Write a README inside the bundle
    readme_lines = [
        f"# Campaign Plan Export",
        f"",
        f"**Run ID:** `{run_id}`",
        f"",
        f"## Contents",
        "",
    ]
    for f in included:
        readme_lines.append(f"- `{f}`")
    if skipped:
        readme_lines += ["", "## Not Included (missing from run)", ""]
        for f in skipped:
            readme_lines.append(f"- `{f}` — not yet generated")
    readme_lines += [
        "",
        "---",
        "*Generated by Campaign In A Box. Individual voter data is never included.*",
    ]
    (bundle_dir / "README.md").write_text("\n".join(readme_lines), encoding="utf-8")
    included.append("README.md")

    # Create ZIP
    zip_path = None
    if create_zip:
        try:
            zip_base = EXPORT_DIR / f"{run_id}__campaign_plan"
            zip_path = Path(shutil.make_archive(str(zip_base), "zip", bundle_dir))
            log.info(f"[EXPORTER] ZIP created: {zip_path}")
        except Exception as e:
            log.warning(f"[EXPORTER] Could not create ZIP: {e}")

    return {
        "bundle_dir": bundle_dir,
        "zip_path": zip_path,
        "files_included": included,
        "files_skipped": skipped,
    }
